// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqfinjkmqvoaecdjenir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZmluamttcXZvYWVjZGplbmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDI0NTIsImV4cCI6MjA2MzMxODQ1Mn0.SnbOTfmGyWSzUSSYUxWx9BKgtkGahcK15DPqEt51Y6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);